### ISSUE TITLE
Your Whole Dump Sucks And I Think You Know It

### ISSUE THREAD

**Issue by dr-NHA** [Primexz/GTAV-Decompiled-Scripts#4]
First Of All Why Does Your Dumps Not Include The Correct Information?
Incorrect Locals And Renamed Things Compared To Other Dumps Forcing Me To Stop Using Your Dumps Out Of Compatiblity Reasons

**Comment by Primexz** [comment]
Okay.
It would be very good if you could give examples where things are wrong in the scripts.

**Comment by dr-NHA** [comment]
int num;
int i;
int num2;
int num3;
int num4;
int num5;
Why Are These Not IVars?
I Know It USUALLY Wouldnt Matter,
BUT Changing Things Like This Rersult In Errors In Applications That Scan Said Scripts

**Comment by dr-NHA** [comment]
Yeah You Close It But See No Issue With Your Dumps,
Its All Good,
From Now On Everyone Can Use My Dumps.
My Dumps Were Done Without Using The Crappy Decompiler XD
Instead Using Sainans!
